name: Report Deployment to GitHub

on:
  push:
    branches:
      - main  # הענף שבו את רוצה להריץ את ה-Workflow

jobs:
  report-deployment:
    runs-on: ubuntu-latest
    permissions:
      deployments: write  # הרשאות כתיבה לדפלוימנט

    steps:
      - name: Report Deployment to GitHub
        uses: actions/github-script@v6
        with:
          script: |
            const { data: deployment } = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              auto_merge: false,
              required_contexts: [],
              payload: { custom_data: "example" }  // עדכני את המידע המותאם לצרכים שלך
            });
            console.log('Deployment reported:', deployment);
